inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/geo_works/derivatives/processors/gdal.rb'
    - 'lib/geo_works/derivatives/processors/image.rb'
    - 'lib/geo_works/derivatives/specs/**/*'
    - 'lib/tasks/**/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - '*.gemspec'
Naming/FileName:
  Exclude: 
   - "geo_works-derivatives.gemspec"
   - "Gemfile"
