---
version: 2
jobs:
  build:
    working_directory: ~/geo_works
    docker:
      - image: circleci/ruby:2.7.5-node-browsers
    steps:
      - checkout
      - run: sudo apt update -y
      - run: sudo apt-get install gdal-bin libgdal-dev libcairo2-dev libpango1.0-dev python3-pip python-is-python3
      - run: sudo sh bin/ci_simple_tiles_install.sh
      # Install Bundler
      - run: gem install bundler -v '2.2.14'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - persist_to_workspace:
          root: '~/geo_works'
          paths: '*'
  test:
    working_directory: ~/geo_works
    docker:
      - image: circleci/ruby:2.7.5-node-browsers
    steps:
      - attach_workspace:
          at: '~/geo_works'
      - run: sudo apt update -y
      - run: sudo apt-get install gdal-bin libgdal-dev libcairo2-dev libpango1.0-dev python3-pip python-is-python3
      - run: sudo sh bin/ci_simple_tiles_install.sh
      # Install Bundler
      - run: gem install bundler -v '2.2.14'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
