version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.2.5
  node: circleci/node@5.0.2
jobs:
  build:
    working_directory: ~/geo_works
    docker:
      - image: cimg/ruby:2.7.5-browsers
    steps:
      - checkout
      - run: sudo apt update -y
      - run: sudo apt-get install gdal-bin libgdal-dev
      - node/install:
          install-yarn: false
          node-version: '12.16.1'
      - run:
          name: Check current version of node
          command: node -v
      # Restore Cached Dependencies
      - run: gem install bundler -v '2.2.14'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run:
          name: Install mapnik
          command: npm install mapnik
      - persist_to_workspace:
          root: '~/geo_works'
          paths: '*'
  test:
    working_directory: ~/geo_works
    docker:
      - image: cimg/ruby:2.7.5-browsers
    steps:
      - attach_workspace:
          at: '~/geo_works'
      - run: sudo apt update -y
      - run: sudo apt-get install gdal-bin libgdal-dev
      - node/install:
          install-yarn: false
          node-version: '12.16.1'
      - run:
          name: Check current version of node
          command: node -v
      - run: gem install bundler -v '2.2.14'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: bundle exec rspec
  rubocop:
    working_directory: ~/geo_works
    docker:
      - image: cimg/ruby:2.7.5-browsers
    steps:
      - attach_workspace:
          at: '~/geo_works'
      - run: gem install bundler -v '2.2.14'
      # Bundle install dependencies
      - run: bundle install --path vendor/bundle
      - run: bundle exec rubocop
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - rubocop:
          requires:
            - build
